FROM alpine:3.4

COPY requirements.txt /app/requirements.txt
COPY src/test/requirements.txt /app/test-requirements.txt

RUN apk add --update \
    git \
    g++ \
    python \
    python-dev \
    py-pip \
    py-dbus \
  && pip install -r /app/requirements.txt \
  && pip install -r /app/test-requirements.txt \
  && apk del \
     git \
     g++ \
     python-dev \
  && rm -rf /var/cache/apk/*

COPY src/ /app
WORKDIR /app

VOLUME '/build'

ENTRYPOINT [ "nosetests", \
	"--with-xunit", "--xunit-file=/build/nosetests.xml", \
	"--with-coverage", "--cover-package=spacel", "--cover-xml", "--cover-xml-file=/build/coverage.xml", \
        "test/"]
